spring:
  application:
    name: backend

  config:
    import: optional:classpath:.env.${spring.profiles.active}[.properties]

  ai:
    mcp:
      server:
        name: qlmcp
        version: 1.0.0
        instructions: You are QL-MCP, an AI assistant designed to help users with their queries. Provide clear and concise answers.
        capabilities:
          prompt: false
          tool: true
          resource: false
          completion: false
        prompt-change-notification: true
        resource-change-notification: false
        tool-change-notification: true
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse
        request-timeout: 180s
        type: sync

      client:
        enabled: true
        initialized: true
        name: qlmcp
        request-timeout: 20s
        root-change-notification: true
        type: sync
        version: 1.0.0
        sse:
          connections:
            weather-mcp:
              url: http://localhost:8888

    openai:
      api-key: ${AI_API_KEY}
      base-url: ${AI_API_BASE_URL}
      chat:
        options:
          model: ${AI_API_MODEL}
          reasoning-effort: none