server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SSL_TYPE}
    key-alias: ${SSL_KEY_ALIAS}

config:
  resource-server-url: ${RESOURCE_SERVER_URL:http://localhost:8080}
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}
