spring:
  application:
    name: backend

  config:
    import:
      - classpath:application-ai.yml
      - classpath:application-mcp-client.yml
      - classpath:application-mcp-server.yml
      - classpath:application-database.yml
      - classpath:application-security.yml
      - classpath:application-config.yml

  profiles:
    default: dev
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:file:.env[.properties]
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - aws-parameterstore:/qlmcp/${PARAM_ENV:prod}/backend/ai/
      - aws-parameterstore:/qlmcp/${PARAM_ENV:prod}/backend/config/
      - aws-parameterstore:/qlmcp/${PARAM_ENV:prod}/backend/database/
      - aws-parameterstore:/qlmcp/${PARAM_ENV:prod}/backend/mcpServer/
      - aws-parameterstore:/qlmcp/${PARAM_ENV:prod}/backend/security/
