spring:
  application:
    name: backend

  config:
    import: optional:classpath:.env.${spring.profiles.active}[.properties]

ai:
  mcp:
    protocolVersion: 2025-06-18
    serverName: qlmcp
    serverVersion: 1.0.0

  api:
    key: ${AI_API_KEY}
    baseUrl: ${AI_API_BASE_URL}
    model: ${AI_API_MODEL}
    type: ${AI_API_TYPE}