spring:
  application:
    name: backend

  config:
    import:
      - classpath:application-ai.yml
      - classpath:application-mcp-client.yml
      - classpath:application-mcp-server.yml
      - classpath:application-database.yml
      - classpath:application-security.yml
      - classpath:application-config.yml

  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - aws-parameterstore:/qlmcp/prod/
---
spring:
  config:
    activate:
      on-profile: test
  ai:
    openai:
      api-key: test-API-key
      base-url: http://test-api-url

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: test-github-clinet-id
            client-secret: test-github-clinet-secret
          google:
            client-id: test-google-client-id
            client-secret: test-google-client-secret

jwt:
  secret: this-is-jwt-secret-this-is-jwt-secret-this-is-jwt-secret
