spring:
  ai:
    mcp:
      server:
        name: QLMCP
        version: 1.1.0
        intructions: AI assistant designed to help users with their queries. Provide clear and concise answers.
        capabilities:
          prompt: false
          tool: true
          resource: false
          completion: false
        prompt-change-notification: true
        resource-change-notification: false
        tool-change-notification: true
        request-timeout: 180s
        type: sync
        protocol: streamable
